ALTER TABLE visit ADD COLUMN deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE visit ADD COLUMN deleted_timestamp TIMESTAMP;
ALTER TABLE visit ADD COLUMN patient_initiated TINYINT(1) NOT NULL DEFAULT 0;