CREATE TABLE media (
	id          VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
	mime_type   VARCHAR(128) NOT NULL,
	owner_type  VARCHAR(32) NOT NULL,
	owner_id    VARCHAR(128) NOT NULL,
	size_bytes  INT UNSIGNED NOT NULL,
	duration_ns BIGINT UNSIGNED NOT NULL,
	created     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_media PRIMARY KEY (id)
);