ALTER TABLE threads MODIFY created TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE thread_items ADD COLUMN deleted BOOL NOT NULL DEFAULT false;
ALTER TABLE thread_items ADD COLUMN modified TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
UPDATE thread_items SET modified = created;
