// Code generated by protoc-gen-gogo.
// source: svc.proto
// DO NOT EDIT!

/*
	Package media is a generated protocol buffer package.

	It is generated from these files:
		svc.proto

	It has these top-level messages:
		MIME
		MediaInfo
		MediaInfosRequest
		MediaInfosResponse
		ClaimMediaRequest
		ClaimMediaResponse
*/
package media

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strconv "strconv"

import strings "strings"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
import sort "sort"
import reflect "reflect"
import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import errors "errors"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

type MediaInfo_OwnerType int32

const (
	MediaInfo_OWNER_TYPE_UNKNOWN MediaInfo_OwnerType = 0
	MediaInfo_ENTITY             MediaInfo_OwnerType = 1
	MediaInfo_ORGANIZATION       MediaInfo_OwnerType = 2
	MediaInfo_THREAD             MediaInfo_OwnerType = 3
	MediaInfo_ACCOUNT            MediaInfo_OwnerType = 4
)

var MediaInfo_OwnerType_name = map[int32]string{
	0: "OWNER_TYPE_UNKNOWN",
	1: "ENTITY",
	2: "ORGANIZATION",
	3: "THREAD",
	4: "ACCOUNT",
}
var MediaInfo_OwnerType_value = map[string]int32{
	"OWNER_TYPE_UNKNOWN": 0,
	"ENTITY":             1,
	"ORGANIZATION":       2,
	"THREAD":             3,
	"ACCOUNT":            4,
}

func (MediaInfo_OwnerType) EnumDescriptor() ([]byte, []int) { return fileDescriptorSvc, []int{1, 0} }

type ClaimMediaRequest_OwnerType int32

const (
	ClaimMediaRequest_OWNER_TYPE_UNKNOWN ClaimMediaRequest_OwnerType = 0
	ClaimMediaRequest_ENTITY             ClaimMediaRequest_OwnerType = 1
	ClaimMediaRequest_ORGANIZATION       ClaimMediaRequest_OwnerType = 2
	ClaimMediaRequest_THREAD             ClaimMediaRequest_OwnerType = 3
	ClaimMediaRequest_ACCOUNT            ClaimMediaRequest_OwnerType = 4
)

var ClaimMediaRequest_OwnerType_name = map[int32]string{
	0: "OWNER_TYPE_UNKNOWN",
	1: "ENTITY",
	2: "ORGANIZATION",
	3: "THREAD",
	4: "ACCOUNT",
}
var ClaimMediaRequest_OwnerType_value = map[string]int32{
	"OWNER_TYPE_UNKNOWN": 0,
	"ENTITY":             1,
	"ORGANIZATION":       2,
	"THREAD":             3,
	"ACCOUNT":            4,
}

func (ClaimMediaRequest_OwnerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorSvc, []int{4, 0}
}

type MIME struct {
	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Subtype string `protobuf:"bytes,2,opt,name=subtype,proto3" json:"subtype,omitempty"`
}

func (m *MIME) Reset()                    { *m = MIME{} }
func (*MIME) ProtoMessage()               {}
func (*MIME) Descriptor() ([]byte, []int) { return fileDescriptorSvc, []int{0} }

type MediaInfo struct {
	ID         string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	URL        string              `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ThumbURL   string              `protobuf:"bytes,3,opt,name=thumb_url,proto3" json:"thumb_url,omitempty"`
	OwnerID    string              `protobuf:"bytes,4,opt,name=owner_id,proto3" json:"owner_id,omitempty"`
	OwnerType  MediaInfo_OwnerType `protobuf:"varint,5,opt,name=owner_type,proto3,enum=media.MediaInfo_OwnerType" json:"owner_type,omitempty"`
	SizeBytes  uint64              `protobuf:"varint,6,opt,name=size_bytes,proto3" json:"size_bytes,omitempty"`
	DurationNS uint64              `protobuf:"varint,7,opt,name=duration_ns,proto3" json:"duration_ns,omitempty"`
	MIME       *MIME               `protobuf:"bytes,8,opt,name=mime" json:"mime,omitempty"`
}

func (m *MediaInfo) Reset()                    { *m = MediaInfo{} }
func (*MediaInfo) ProtoMessage()               {}
func (*MediaInfo) Descriptor() ([]byte, []int) { return fileDescriptorSvc, []int{1} }

func (m *MediaInfo) GetMIME() *MIME {
	if m != nil {
		return m.MIME
	}
	return nil
}

type MediaInfosRequest struct {
	MediaIDs []string `protobuf:"bytes,1,rep,name=media_ids" json:"media_ids,omitempty"`
}

func (m *MediaInfosRequest) Reset()                    { *m = MediaInfosRequest{} }
func (*MediaInfosRequest) ProtoMessage()               {}
func (*MediaInfosRequest) Descriptor() ([]byte, []int) { return fileDescriptorSvc, []int{2} }

type MediaInfosResponse struct {
	MediaInfos map[string]*MediaInfo `protobuf:"bytes,1,rep,name=media_infos" json:"media_infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MediaInfosResponse) Reset()                    { *m = MediaInfosResponse{} }
func (*MediaInfosResponse) ProtoMessage()               {}
func (*MediaInfosResponse) Descriptor() ([]byte, []int) { return fileDescriptorSvc, []int{3} }

func (m *MediaInfosResponse) GetMediaInfos() map[string]*MediaInfo {
	if m != nil {
		return m.MediaInfos
	}
	return nil
}

type ClaimMediaRequest struct {
	MediaIDs  []string                    `protobuf:"bytes,1,rep,name=media_ids" json:"media_ids,omitempty"`
	OwnerType ClaimMediaRequest_OwnerType `protobuf:"varint,2,opt,name=owner_type,proto3,enum=media.ClaimMediaRequest_OwnerType" json:"owner_type,omitempty"`
	OwnerID   string                      `protobuf:"bytes,3,opt,name=owner_id,proto3" json:"owner_id,omitempty"`
}

func (m *ClaimMediaRequest) Reset()                    { *m = ClaimMediaRequest{} }
func (*ClaimMediaRequest) ProtoMessage()               {}
func (*ClaimMediaRequest) Descriptor() ([]byte, []int) { return fileDescriptorSvc, []int{4} }

type ClaimMediaResponse struct {
}

func (m *ClaimMediaResponse) Reset()                    { *m = ClaimMediaResponse{} }
func (*ClaimMediaResponse) ProtoMessage()               {}
func (*ClaimMediaResponse) Descriptor() ([]byte, []int) { return fileDescriptorSvc, []int{5} }

func init() {
	proto.RegisterType((*MIME)(nil), "media.MIME")
	proto.RegisterType((*MediaInfo)(nil), "media.MediaInfo")
	proto.RegisterType((*MediaInfosRequest)(nil), "media.MediaInfosRequest")
	proto.RegisterType((*MediaInfosResponse)(nil), "media.MediaInfosResponse")
	proto.RegisterType((*ClaimMediaRequest)(nil), "media.ClaimMediaRequest")
	proto.RegisterType((*ClaimMediaResponse)(nil), "media.ClaimMediaResponse")
	proto.RegisterEnum("media.MediaInfo_OwnerType", MediaInfo_OwnerType_name, MediaInfo_OwnerType_value)
	proto.RegisterEnum("media.ClaimMediaRequest_OwnerType", ClaimMediaRequest_OwnerType_name, ClaimMediaRequest_OwnerType_value)
}
func (x MediaInfo_OwnerType) String() string {
	s, ok := MediaInfo_OwnerType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x ClaimMediaRequest_OwnerType) String() string {
	s, ok := ClaimMediaRequest_OwnerType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *MIME) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*MIME)
	if !ok {
		that2, ok := that.(MIME)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Subtype != that1.Subtype {
		return false
	}
	return true
}
func (this *MediaInfo) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*MediaInfo)
	if !ok {
		that2, ok := that.(MediaInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.URL != that1.URL {
		return false
	}
	if this.ThumbURL != that1.ThumbURL {
		return false
	}
	if this.OwnerID != that1.OwnerID {
		return false
	}
	if this.OwnerType != that1.OwnerType {
		return false
	}
	if this.SizeBytes != that1.SizeBytes {
		return false
	}
	if this.DurationNS != that1.DurationNS {
		return false
	}
	if !this.MIME.Equal(that1.MIME) {
		return false
	}
	return true
}
func (this *MediaInfosRequest) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*MediaInfosRequest)
	if !ok {
		that2, ok := that.(MediaInfosRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.MediaIDs) != len(that1.MediaIDs) {
		return false
	}
	for i := range this.MediaIDs {
		if this.MediaIDs[i] != that1.MediaIDs[i] {
			return false
		}
	}
	return true
}
func (this *MediaInfosResponse) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*MediaInfosResponse)
	if !ok {
		that2, ok := that.(MediaInfosResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.MediaInfos) != len(that1.MediaInfos) {
		return false
	}
	for i := range this.MediaInfos {
		if !this.MediaInfos[i].Equal(that1.MediaInfos[i]) {
			return false
		}
	}
	return true
}
func (this *ClaimMediaRequest) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*ClaimMediaRequest)
	if !ok {
		that2, ok := that.(ClaimMediaRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.MediaIDs) != len(that1.MediaIDs) {
		return false
	}
	for i := range this.MediaIDs {
		if this.MediaIDs[i] != that1.MediaIDs[i] {
			return false
		}
	}
	if this.OwnerType != that1.OwnerType {
		return false
	}
	if this.OwnerID != that1.OwnerID {
		return false
	}
	return true
}
func (this *ClaimMediaResponse) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*ClaimMediaResponse)
	if !ok {
		that2, ok := that.(ClaimMediaResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	return true
}
func (this *MIME) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&media.MIME{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Subtype: "+fmt.Sprintf("%#v", this.Subtype)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MediaInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&media.MediaInfo{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "URL: "+fmt.Sprintf("%#v", this.URL)+",\n")
	s = append(s, "ThumbURL: "+fmt.Sprintf("%#v", this.ThumbURL)+",\n")
	s = append(s, "OwnerID: "+fmt.Sprintf("%#v", this.OwnerID)+",\n")
	s = append(s, "OwnerType: "+fmt.Sprintf("%#v", this.OwnerType)+",\n")
	s = append(s, "SizeBytes: "+fmt.Sprintf("%#v", this.SizeBytes)+",\n")
	s = append(s, "DurationNS: "+fmt.Sprintf("%#v", this.DurationNS)+",\n")
	if this.MIME != nil {
		s = append(s, "MIME: "+fmt.Sprintf("%#v", this.MIME)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MediaInfosRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&media.MediaInfosRequest{")
	s = append(s, "MediaIDs: "+fmt.Sprintf("%#v", this.MediaIDs)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MediaInfosResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&media.MediaInfosResponse{")
	keysForMediaInfos := make([]string, 0, len(this.MediaInfos))
	for k, _ := range this.MediaInfos {
		keysForMediaInfos = append(keysForMediaInfos, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForMediaInfos)
	mapStringForMediaInfos := "map[string]*MediaInfo{"
	for _, k := range keysForMediaInfos {
		mapStringForMediaInfos += fmt.Sprintf("%#v: %#v,", k, this.MediaInfos[k])
	}
	mapStringForMediaInfos += "}"
	if this.MediaInfos != nil {
		s = append(s, "MediaInfos: "+mapStringForMediaInfos+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ClaimMediaRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&media.ClaimMediaRequest{")
	s = append(s, "MediaIDs: "+fmt.Sprintf("%#v", this.MediaIDs)+",\n")
	s = append(s, "OwnerType: "+fmt.Sprintf("%#v", this.OwnerType)+",\n")
	s = append(s, "OwnerID: "+fmt.Sprintf("%#v", this.OwnerID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ClaimMediaResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&media.ClaimMediaResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSvc(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func extensionToGoStringSvc(e map[int32]github_com_gogo_protobuf_proto.Extension) string {
	if e == nil {
		return "nil"
	}
	s := "map[int32]proto.Extension{"
	keys := make([]int, 0, len(e))
	for k := range e {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	ss := []string{}
	for _, k := range keys {
		ss = append(ss, strconv.Itoa(k)+": "+e[int32(k)].GoString())
	}
	s += strings.Join(ss, ",") + "}"
	return s
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Media service

type MediaClient interface {
	ClaimMedia(ctx context.Context, in *ClaimMediaRequest, opts ...grpc.CallOption) (*ClaimMediaResponse, error)
	MediaInfos(ctx context.Context, in *MediaInfosRequest, opts ...grpc.CallOption) (*MediaInfosResponse, error)
}

type mediaClient struct {
	cc *grpc.ClientConn
}

func NewMediaClient(cc *grpc.ClientConn) MediaClient {
	return &mediaClient{cc}
}

func (c *mediaClient) ClaimMedia(ctx context.Context, in *ClaimMediaRequest, opts ...grpc.CallOption) (*ClaimMediaResponse, error) {
	out := new(ClaimMediaResponse)
	err := grpc.Invoke(ctx, "/media.Media/ClaimMedia", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaClient) MediaInfos(ctx context.Context, in *MediaInfosRequest, opts ...grpc.CallOption) (*MediaInfosResponse, error) {
	out := new(MediaInfosResponse)
	err := grpc.Invoke(ctx, "/media.Media/MediaInfos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Media service

type MediaServer interface {
	ClaimMedia(context.Context, *ClaimMediaRequest) (*ClaimMediaResponse, error)
	MediaInfos(context.Context, *MediaInfosRequest) (*MediaInfosResponse, error)
}

func RegisterMediaServer(s *grpc.Server, srv MediaServer) {
	s.RegisterService(&_Media_serviceDesc, srv)
}

func _Media_ClaimMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServer).ClaimMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.Media/ClaimMedia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServer).ClaimMedia(ctx, req.(*ClaimMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Media_MediaInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServer).MediaInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.Media/MediaInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServer).MediaInfos(ctx, req.(*MediaInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Media_serviceDesc = grpc.ServiceDesc{
	ServiceName: "media.Media",
	HandlerType: (*MediaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimMedia",
			Handler:    _Media_ClaimMedia_Handler,
		},
		{
			MethodName: "MediaInfos",
			Handler:    _Media_MediaInfos_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

func (m *MIME) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MIME) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Type) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintSvc(data, i, uint64(len(m.Type)))
		i += copy(data[i:], m.Type)
	}
	if len(m.Subtype) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintSvc(data, i, uint64(len(m.Subtype)))
		i += copy(data[i:], m.Subtype)
	}
	return i, nil
}

func (m *MediaInfo) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MediaInfo) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintSvc(data, i, uint64(len(m.ID)))
		i += copy(data[i:], m.ID)
	}
	if len(m.URL) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintSvc(data, i, uint64(len(m.URL)))
		i += copy(data[i:], m.URL)
	}
	if len(m.ThumbURL) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintSvc(data, i, uint64(len(m.ThumbURL)))
		i += copy(data[i:], m.ThumbURL)
	}
	if len(m.OwnerID) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintSvc(data, i, uint64(len(m.OwnerID)))
		i += copy(data[i:], m.OwnerID)
	}
	if m.OwnerType != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintSvc(data, i, uint64(m.OwnerType))
	}
	if m.SizeBytes != 0 {
		data[i] = 0x30
		i++
		i = encodeVarintSvc(data, i, uint64(m.SizeBytes))
	}
	if m.DurationNS != 0 {
		data[i] = 0x38
		i++
		i = encodeVarintSvc(data, i, uint64(m.DurationNS))
	}
	if m.MIME != nil {
		data[i] = 0x42
		i++
		i = encodeVarintSvc(data, i, uint64(m.MIME.Size()))
		n1, err := m.MIME.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *MediaInfosRequest) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MediaInfosRequest) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.MediaIDs) > 0 {
		for _, s := range m.MediaIDs {
			data[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				data[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			data[i] = uint8(l)
			i++
			i += copy(data[i:], s)
		}
	}
	return i, nil
}

func (m *MediaInfosResponse) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MediaInfosResponse) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.MediaInfos) > 0 {
		for k, _ := range m.MediaInfos {
			data[i] = 0xa
			i++
			v := m.MediaInfos[k]
			if v == nil {
				return 0, errors.New("proto: map has nil element")
			}
			msgSize := v.Size()
			mapSize := 1 + len(k) + sovSvc(uint64(len(k))) + 1 + msgSize + sovSvc(uint64(msgSize))
			i = encodeVarintSvc(data, i, uint64(mapSize))
			data[i] = 0xa
			i++
			i = encodeVarintSvc(data, i, uint64(len(k)))
			i += copy(data[i:], k)
			data[i] = 0x12
			i++
			i = encodeVarintSvc(data, i, uint64(v.Size()))
			n2, err := v.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n2
		}
	}
	return i, nil
}

func (m *ClaimMediaRequest) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ClaimMediaRequest) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.MediaIDs) > 0 {
		for _, s := range m.MediaIDs {
			data[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				data[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			data[i] = uint8(l)
			i++
			i += copy(data[i:], s)
		}
	}
	if m.OwnerType != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintSvc(data, i, uint64(m.OwnerType))
	}
	if len(m.OwnerID) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintSvc(data, i, uint64(len(m.OwnerID)))
		i += copy(data[i:], m.OwnerID)
	}
	return i, nil
}

func (m *ClaimMediaResponse) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ClaimMediaResponse) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeFixed64Svc(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Svc(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintSvc(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *MIME) Size() (n int) {
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovSvc(uint64(l))
	}
	l = len(m.Subtype)
	if l > 0 {
		n += 1 + l + sovSvc(uint64(l))
	}
	return n
}

func (m *MediaInfo) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovSvc(uint64(l))
	}
	l = len(m.URL)
	if l > 0 {
		n += 1 + l + sovSvc(uint64(l))
	}
	l = len(m.ThumbURL)
	if l > 0 {
		n += 1 + l + sovSvc(uint64(l))
	}
	l = len(m.OwnerID)
	if l > 0 {
		n += 1 + l + sovSvc(uint64(l))
	}
	if m.OwnerType != 0 {
		n += 1 + sovSvc(uint64(m.OwnerType))
	}
	if m.SizeBytes != 0 {
		n += 1 + sovSvc(uint64(m.SizeBytes))
	}
	if m.DurationNS != 0 {
		n += 1 + sovSvc(uint64(m.DurationNS))
	}
	if m.MIME != nil {
		l = m.MIME.Size()
		n += 1 + l + sovSvc(uint64(l))
	}
	return n
}

func (m *MediaInfosRequest) Size() (n int) {
	var l int
	_ = l
	if len(m.MediaIDs) > 0 {
		for _, s := range m.MediaIDs {
			l = len(s)
			n += 1 + l + sovSvc(uint64(l))
		}
	}
	return n
}

func (m *MediaInfosResponse) Size() (n int) {
	var l int
	_ = l
	if len(m.MediaInfos) > 0 {
		for k, v := range m.MediaInfos {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
			}
			mapEntrySize := 1 + len(k) + sovSvc(uint64(len(k))) + 1 + l + sovSvc(uint64(l))
			n += mapEntrySize + 1 + sovSvc(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *ClaimMediaRequest) Size() (n int) {
	var l int
	_ = l
	if len(m.MediaIDs) > 0 {
		for _, s := range m.MediaIDs {
			l = len(s)
			n += 1 + l + sovSvc(uint64(l))
		}
	}
	if m.OwnerType != 0 {
		n += 1 + sovSvc(uint64(m.OwnerType))
	}
	l = len(m.OwnerID)
	if l > 0 {
		n += 1 + l + sovSvc(uint64(l))
	}
	return n
}

func (m *ClaimMediaResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovSvc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSvc(x uint64) (n int) {
	return sovSvc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *MIME) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MIME{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Subtype:` + fmt.Sprintf("%v", this.Subtype) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MediaInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MediaInfo{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`URL:` + fmt.Sprintf("%v", this.URL) + `,`,
		`ThumbURL:` + fmt.Sprintf("%v", this.ThumbURL) + `,`,
		`OwnerID:` + fmt.Sprintf("%v", this.OwnerID) + `,`,
		`OwnerType:` + fmt.Sprintf("%v", this.OwnerType) + `,`,
		`SizeBytes:` + fmt.Sprintf("%v", this.SizeBytes) + `,`,
		`DurationNS:` + fmt.Sprintf("%v", this.DurationNS) + `,`,
		`MIME:` + strings.Replace(fmt.Sprintf("%v", this.MIME), "MIME", "MIME", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MediaInfosRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MediaInfosRequest{`,
		`MediaIDs:` + fmt.Sprintf("%v", this.MediaIDs) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MediaInfosResponse) String() string {
	if this == nil {
		return "nil"
	}
	keysForMediaInfos := make([]string, 0, len(this.MediaInfos))
	for k, _ := range this.MediaInfos {
		keysForMediaInfos = append(keysForMediaInfos, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForMediaInfos)
	mapStringForMediaInfos := "map[string]*MediaInfo{"
	for _, k := range keysForMediaInfos {
		mapStringForMediaInfos += fmt.Sprintf("%v: %v,", k, this.MediaInfos[k])
	}
	mapStringForMediaInfos += "}"
	s := strings.Join([]string{`&MediaInfosResponse{`,
		`MediaInfos:` + mapStringForMediaInfos + `,`,
		`}`,
	}, "")
	return s
}
func (this *ClaimMediaRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClaimMediaRequest{`,
		`MediaIDs:` + fmt.Sprintf("%v", this.MediaIDs) + `,`,
		`OwnerType:` + fmt.Sprintf("%v", this.OwnerType) + `,`,
		`OwnerID:` + fmt.Sprintf("%v", this.OwnerID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ClaimMediaResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClaimMediaResponse{`,
		`}`,
	}, "")
	return s
}
func valueToStringSvc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *MIME) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MIME: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MIME: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subtype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subtype = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MediaInfo) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MediaInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MediaInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URL = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThumbURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThumbURL = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerID = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerType", wireType)
			}
			m.OwnerType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.OwnerType |= (MediaInfo_OwnerType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SizeBytes", wireType)
			}
			m.SizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SizeBytes |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationNS", wireType)
			}
			m.DurationNS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.DurationNS |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MIME", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MIME == nil {
				m.MIME = &MIME{}
			}
			if err := m.MIME.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MediaInfosRequest) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MediaInfosRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MediaInfosRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MediaIDs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MediaIDs = append(m.MediaIDs, string(data[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MediaInfosResponse) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MediaInfosResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MediaInfosResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MediaInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthSvc
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(data[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			var valuekey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				valuekey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var mapmsglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				mapmsglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if mapmsglen < 0 {
				return ErrInvalidLengthSvc
			}
			postmsgIndex := iNdEx + mapmsglen
			if mapmsglen < 0 {
				return ErrInvalidLengthSvc
			}
			if postmsgIndex > l {
				return io.ErrUnexpectedEOF
			}
			mapvalue := &MediaInfo{}
			if err := mapvalue.Unmarshal(data[iNdEx:postmsgIndex]); err != nil {
				return err
			}
			iNdEx = postmsgIndex
			if m.MediaInfos == nil {
				m.MediaInfos = make(map[string]*MediaInfo)
			}
			m.MediaInfos[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClaimMediaRequest) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimMediaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimMediaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MediaIDs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MediaIDs = append(m.MediaIDs, string(data[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerType", wireType)
			}
			m.OwnerType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.OwnerType |= (ClaimMediaRequest_OwnerType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerID = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClaimMediaResponse) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimMediaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimMediaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSvc(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSvc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSvc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSvc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSvc(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSvc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSvc   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorSvc = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0x4f, 0x8b, 0xd3, 0x5e,
	0x14, 0x6d, 0xfe, 0xf4, 0xdf, 0x4d, 0x7f, 0x33, 0x99, 0xc7, 0xf0, 0xa3, 0x16, 0x6c, 0x25, 0x22,
	0x28, 0x68, 0x07, 0xaa, 0x88, 0x08, 0x0a, 0x4d, 0x1b, 0x34, 0x68, 0x53, 0xa9, 0x29, 0x32, 0xb3,
	0x09, 0xcd, 0x34, 0x53, 0x83, 0x4d, 0x52, 0xfb, 0x92, 0x91, 0xba, 0xf2, 0x0b, 0x08, 0x6e, 0xfd,
	0x06, 0x7e, 0x14, 0x97, 0xb3, 0x74, 0x25, 0x4e, 0x5d, 0xe8, 0x4a, 0xfc, 0x08, 0xde, 0xbc, 0x74,
	0xd2, 0x4e, 0xab, 0xe0, 0xc6, 0xc5, 0x23, 0x7d, 0xe7, 0x9c, 0x7b, 0xdf, 0x7d, 0xe7, 0x1d, 0x0a,
	0x45, 0x7a, 0x7c, 0x58, 0x9f, 0x4c, 0x83, 0x30, 0x20, 0x59, 0xcf, 0x19, 0xba, 0x83, 0xca, 0x8d,
	0x91, 0x1b, 0x3e, 0x8f, 0xec, 0xfa, 0x61, 0xe0, 0xed, 0x8d, 0x82, 0x51, 0xb0, 0xc7, 0x58, 0x3b,
	0x3a, 0x62, 0x3b, 0xb6, 0x61, 0xbf, 0x92, 0x2a, 0xe5, 0x0a, 0x88, 0x1d, 0xbd, 0xa3, 0x91, 0x12,
	0x88, 0xe1, 0x6c, 0xe2, 0x94, 0xb9, 0x4b, 0xdc, 0xd5, 0x22, 0xd9, 0x86, 0x3c, 0x8d, 0x6c, 0x06,
	0xf0, 0x31, 0xa0, 0xfc, 0xe0, 0xa1, 0xd8, 0x89, 0xfb, 0xeb, 0xfe, 0x51, 0x40, 0x08, 0xf0, 0xee,
	0x30, 0x91, 0xaa, 0xb9, 0xf9, 0xe7, 0x1a, 0xaf, 0xb7, 0xc9, 0x2e, 0x08, 0xd1, 0x74, 0x9c, 0xc8,
	0xd5, 0x3c, 0x82, 0x42, 0xbf, 0xf7, 0x98, 0xd4, 0xa0, 0x88, 0xd3, 0x78, 0xb6, 0x15, 0x73, 0x02,
	0xe3, 0x4a, 0xc8, 0x15, 0xcc, 0x18, 0x8c, 0x05, 0x17, 0xa1, 0x10, 0xbc, 0xf2, 0x9d, 0xa9, 0x85,
	0x0d, 0x45, 0xc6, 0x4b, 0xc8, 0xe7, 0xbb, 0x31, 0x86, 0x5d, 0xef, 0x01, 0x24, 0x34, 0x9b, 0x25,
	0x8b, 0x82, 0xad, 0x46, 0xa5, 0xce, 0x6e, 0x5a, 0x4f, 0xe7, 0xa9, 0x33, 0xb5, 0x89, 0x0a, 0xf5,
	0x3f, 0x2c, 0x2e, 0xa6, 0x5b, 0x1c, 0x14, 0xa8, 0xfb, 0xda, 0xb1, 0xec, 0x59, 0xe8, 0xd0, 0x72,
	0x0e, 0xcb, 0x45, 0x72, 0x19, 0xa4, 0x61, 0x34, 0x1d, 0x84, 0x6e, 0xe0, 0x5b, 0x3e, 0x2d, 0xe7,
	0x63, 0x50, 0xdd, 0xc2, 0x3a, 0x68, 0x2f, 0x60, 0xe3, 0x29, 0x8a, 0x44, 0xcf, 0xf5, 0x9c, 0x72,
	0x01, 0x59, 0xa9, 0x21, 0x9d, 0x9d, 0x88, 0x4e, 0xa9, 0x05, 0x94, 0x32, 0xcf, 0x94, 0x03, 0x58,
	0x39, 0xea, 0x7f, 0x20, 0xdd, 0x67, 0x86, 0xd6, 0xb3, 0xcc, 0xfd, 0x27, 0x9a, 0xd5, 0x37, 0x1e,
	0x19, 0xb8, 0x95, 0x33, 0x38, 0x41, 0x4e, 0x33, 0x4c, 0xdd, 0xdc, 0x97, 0x39, 0x22, 0x43, 0xa9,
	0xdb, 0x7b, 0xd0, 0x34, 0xf4, 0x83, 0xa6, 0xa9, 0x77, 0x0d, 0x99, 0x8f, 0x59, 0xf3, 0x61, 0x4f,
	0x6b, 0xb6, 0x65, 0x81, 0x48, 0x90, 0x6f, 0xb6, 0x5a, 0xdd, 0xbe, 0x61, 0xca, 0xa2, 0x72, 0x0b,
	0x76, 0xd2, 0xfb, 0xd1, 0x9e, 0xf3, 0x32, 0x72, 0x68, 0x18, 0xbb, 0xc9, 0x06, 0x41, 0xb3, 0x28,
	0xda, 0x2f, 0x9c, 0xb9, 0x99, 0x28, 0xdb, 0x54, 0x79, 0xcf, 0x01, 0x59, 0x2d, 0xa3, 0x93, 0xc0,
	0xa7, 0x0e, 0xb9, 0x0f, 0xd2, 0xa2, 0x2e, 0x86, 0x59, 0xa5, 0xd4, 0xb8, 0xb6, 0x6e, 0x63, 0xaa,
	0x5f, 0x81, 0x34, 0x3f, 0x9c, 0xce, 0x2a, 0x2d, 0xd8, 0x5e, 0x83, 0x70, 0x58, 0xe1, 0x85, 0x33,
	0x5b, 0xc4, 0xa5, 0x06, 0xd9, 0xe3, 0xc1, 0x38, 0x4a, 0xc2, 0x22, 0x35, 0xe4, 0xf5, 0xce, 0x77,
	0xf9, 0x3b, 0x9c, 0xf2, 0x8d, 0x83, 0x9d, 0xd6, 0x78, 0xe0, 0x7a, 0x0c, 0xfe, 0xdb, 0x2b, 0x91,
	0xdb, 0xe7, 0x12, 0xc0, 0xb3, 0x04, 0x28, 0x8b, 0x03, 0x36, 0xda, 0x2d, 0x93, 0x70, 0x2e, 0x58,
	0xc2, 0x46, 0xb0, 0xfe, 0xe9, 0xdb, 0xed, 0x02, 0x59, 0x9d, 0x2c, 0x31, 0xb5, 0xf1, 0x96, 0x83,
	0x2c, 0x43, 0x48, 0x13, 0x60, 0xc9, 0x93, 0xf2, 0x9f, 0x2e, 0x53, 0xb9, 0xf0, 0x1b, 0x66, 0xf1,
	0xa2, 0xd8, 0x62, 0xf9, 0x22, 0x69, 0x8b, 0x8d, 0xc4, 0xa4, 0x2d, 0x36, 0x1f, 0x59, 0xbd, 0x7e,
	0x72, 0x5a, 0xe5, 0x3e, 0x9d, 0x56, 0x33, 0x3f, 0xf1, 0xfb, 0x66, 0x5e, 0xe5, 0x3e, 0xe0, 0xfa,
	0x88, 0xeb, 0x04, 0xd7, 0x17, 0x5c, 0xdf, 0xe7, 0xc8, 0xe1, 0xf7, 0xdd, 0xd7, 0x6a, 0xc6, 0xce,
	0xb1, 0xbf, 0x8b, 0x9b, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xed, 0x84, 0xa2, 0xb7, 0x71, 0x04,
	0x00, 0x00,
}
