// This file is automatically generated. Do not modify.

package api

import (
	"fmt"
)

var _ = fmt.Printf

type AccessDenied struct {
	Message string `thrift:"1,required" json:"message"`
}

func (e *AccessDenied) Error() string {
	return fmt.Sprintf("AccessDenied{Message: %+v}", e.Message)
}

type InternalServerError struct {
	Message string `thrift:"1,required" json:"message"`
}

func (e *InternalServerError) Error() string {
	return fmt.Sprintf("InternalServerError{Message: %+v}", e.Message)
}

type OverCapacity struct {
	Message string `thrift:"1,required" json:"message"`
}

func (e *OverCapacity) Error() string {
	return fmt.Sprintf("OverCapacity{Message: %+v}", e.Message)
}
