delete from state;
insert into state (full_name, abbreviation, country) values ('Alabama', 'AL', 'USA');
insert into state (full_name, abbreviation, country) values ('Alaska','AK','USA');
insert into state (full_name, abbreviation, country) values ('Arizona','AZ','USA');
insert into state (full_name, abbreviation, country) values ('Arkansas','AR','USA');
insert into state (full_name, abbreviation, country) values ('California','CA','USA');
insert into state (full_name, abbreviation, country) values ('Colorado','CO','USA');
insert into state (full_name, abbreviation, country) values ('Connecticut','CT','USA');
insert into state (full_name, abbreviation, country) values ('Delaware','DE','USA');
insert into state (full_name, abbreviation, country) values ('Florida','FL','USA');
insert into state (full_name, abbreviation, country) values ('Georgia','GA','USA');
insert into state (full_name, abbreviation, country) values ('Hawaii','HI','USA');
insert into state (full_name, abbreviation, country) values ('Idaho','ID','USA');
insert into state (full_name, abbreviation, country) values ('Illinois','IL','USA');
insert into state (full_name, abbreviation, country) values ('Indiana','IN','USA');
insert into state (full_name, abbreviation, country) values ('Iowa','IA','USA');
insert into state (full_name, abbreviation, country) values ('Kansas','KS','USA');
insert into state (full_name, abbreviation, country) values ('Kentucky','KY','USA');
insert into state (full_name, abbreviation, country) values ('Louisiana','LA','USA');
insert into state (full_name, abbreviation, country) values ('Maine','ME','US');
insert into state (full_name, abbreviation, country) values ('Maryland','MD','USA');
insert into state (full_name, abbreviation, country) values ('Massachusetts','MA','USA');
insert into state (full_name, abbreviation, country) values ('Michigan','MI','USA');
insert into state (full_name, abbreviation, country) values ('Minnesota','MN','USA');
insert into state (full_name, abbreviation, country) values ('Mississippi','MS','USA');
insert into state (full_name, abbreviation, country) values ('Missouri','MO','USA');
insert into state (full_name, abbreviation, country) values ('Montana','MT','USA');
insert into state (full_name, abbreviation, country) values ('Nebraska','NE','USA');
insert into state (full_name, abbreviation, country) values ('Nevada','NV','USA');
insert into state (full_name, abbreviation, country) values ('New Hampshire','NH','USA');
insert into state (full_name, abbreviation, country) values ('New Jersey','NJ','USA');
insert into state (full_name, abbreviation, country) values ('New Mexico','NM','USA');
insert into state (full_name, abbreviation, country) values ('New York','NY','USA');
insert into state (full_name, abbreviation, country) values ('North Carolina','NC','USA');
insert into state (full_name, abbreviation, country) values ('North Dakota','ND','USA');
insert into state (full_name, abbreviation, country) values ('Ohio','OH','USA');
insert into state (full_name, abbreviation, country) values ('Oklahoma','OK','USA');
insert into state (full_name, abbreviation, country) values ('Oregon','OR','USA');
insert into state (full_name, abbreviation, country) values ('Pennsylvania','PA','USA');
insert into state (full_name, abbreviation, country) values ('Rhode Island','RI','USA');
insert into state (full_name, abbreviation, country) values ('South Carolina','SC','USA');
insert into state (full_name, abbreviation, country) values ('South Dakota','SD','USA');
insert into state (full_name, abbreviation, country) values ('Tennessee','TN','USA');
insert into state (full_name, abbreviation, country) values ('Texas','TX','USA');
insert into state (full_name, abbreviation, country) values ('Utah','UT','USA');
insert into state (full_name, abbreviation, country) values ('Vermont','VT','USA');
insert into state (full_name, abbreviation, country) values ('Virginia','VA','USA');
insert into state (full_name, abbreviation, country) values ('Washington','WA','USA');
insert into state (full_name, abbreviation, country) values ('West Virginia','WV','USA');
insert into state (full_name, abbreviation, country) values ('Wisconsin','WI','USA');
insert into state (full_name, abbreviation, country) values ('Wyoming','WY','USA');
