alter table treatment add erx_last_filled_date timestamp;

create table pharmacy_dispensed_treatment (
	id int unsigned not null auto_increment,
	drug_internal_name varchar(250) not null,
	dispense_value int unsigned not null,
	dispense_unit_id int unsigned not null,
	refills int unsigned not null,
	substitutions_allowed tinyint(1) not null,
	days_supply int unsigned not null,
	pharmacy_notes varchar(150) not null,
	pharmacy_id int unsigned not null,
	patient_instructions varchar(150) not null,
	creation_date timestamp not null default current_timestamp,
	status varchar(100) not null,
	dosage_strength varchar(250) not null,
	type varchar(150) not null,
	drug_name_id int unsigned,
	drug_form_id int unsigned,
	drug_route_id int unsigned,
	erx_id int unsigned,
	erx_last_filled_date timestamp,
	erx_sent_date timestamp,
	treatment_id int unsigned not null,
	foreign key (treatment_id) references treatment(id),
	foreign key (drug_name_id) references drug_name(id),
	foreign key (drug_route_id) references drug_route(id),
	foreign key (drug_form_id) references drug_form(id),
	foreign key (dispense_unit_id) references dispense_unit(id),
	foreign key (pharmacy_id) references pharmacy_selection(id),	
	primary key (id)
) character set utf8;

create table unlinked_requested_treatment (
	id int unsigned not null auto_increment,
	drug_internal_name varchar(250) not null,
	dispense_value int unsigned not null,
	dispense_unit_id int unsigned not null,
	refills int unsigned not null,
	substitutions_allowed tinyint(1) not null,
	days_supply int unsigned not null,
	pharmacy_id int unsigned not null,
	pharmacy_notes varchar(150) not null,
	patient_instructions varchar(150) not null,
	creation_date timestamp not null default current_timestamp,
	status varchar(100) not null,
	dosage_strength varchar(250) not null,
	type varchar(150) not null,
	drug_name_id int unsigned,
	drug_form_id int unsigned,
	drug_route_id int unsigned,
	erx_id int unsigned,
	erx_last_filled_date timestamp,
	erx_sent_date timestamp,
	foreign key (drug_name_id) references drug_name(id),
	foreign key (drug_route_id) references drug_route(id),
	foreign key (drug_form_id) references drug_form(id),
	foreign key (dispense_unit_id) references dispense_unit(id),
	foreign key (pharmacy_id) references pharmacy_selection(id),	
	primary key (id)
) character set utf8;

create table rx_refill_request (
	id int unsigned not null auto_increment,
	erx_request_queue_item_id int unsigned,
	reference_number varchar(100),
	pharmacy_rx_reference_number varchar(100),
	requested_drug_description varchar(100) not null,
	requested_refill_amount int unsigned not null,
	requested_dispense varchar(100) not null,
	patient_id int unsigned not null,
	request_date timestamp not null,
	doctor_id int unsigned not null,
	requested_treatment_id int unsigned,
	dispensed_treatment_id int unsigned not null,
	unlinked_requested_treatment_id int unsigned,
	foreign key (requested_treatment_id) references treatment(id),
	foreign key (dispensed_treatment_id) references pharmacy_dispensed_treatment(id),
	foreign key (unlinked_requested_treatment_id) references unlinked_requested_treatment(id),
	foreign key (doctor_id) references doctor(id),
	foreign key (patient_id) references patient(id),
	primary key (id)
) character set utf8;

create table rx_refill_status_events (
	id int unsigned not null auto_increment,
	rx_refill_request_id int unsigned not null,
	rx_refill_status varchar(100) not null,
	status varchar(100) not null,
	rx_refill_status_date timestamp not null,
	reason varchar(100),
	notes varchar(500),
	foreign key (rx_refill_request_id) references rx_refill_request(id),
	primary key (id),
	key (status)
) character set utf8;
