CREATE TABLE resource_guide (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(256) NOT NULL,
	photo_url VARCHAR(256) NOT NULL,
	layout BLOB NOT NULL,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
) CHARACTER SET utf8;
