ALTER TABLE person CHANGE role_id role_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE pending_task CHANGE item_id item_id BIGINT UNSIGNED NOT NULL;

ALTER TABLE credit_card DROP FOREIGN KEY credit_card_ibfk_2;
ALTER TABLE credit_card CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
-- doctor_queue doesn't seem to have a foreign key constraint
ALTER TABLE doctor_queue CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE doctor_transaction DROP FOREIGN KEY doctor_transaction_ibfk_1;
ALTER TABLE doctor_transaction CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE health_log DROP FOREIGN KEY health_log_ibfk_1;
ALTER TABLE health_log CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE info_intake DROP FOREIGN KEY info_intake_ibfk_11;
ALTER TABLE info_intake CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE parent_consent_proof DROP FOREIGN KEY patient_id;
ALTER TABLE parent_consent_proof CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_address_selection DROP FOREIGN KEY patient_address_selection_ibfk_1;
ALTER TABLE patient_address_selection CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_agreement DROP FOREIGN KEY patient_agreement_ibfk_1;
ALTER TABLE patient_agreement CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_care_provider_assignment DROP FOREIGN KEY patient_care_provider_assignment_ibfk_4;
ALTER TABLE patient_care_provider_assignment CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_case DROP FOREIGN KEY patient_case_ibfk_1;
ALTER TABLE patient_case CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_emergency_contact DROP FOREIGN KEY patient_emergency_contact_ibfk_1;
ALTER TABLE patient_emergency_contact CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_exported_medical_record DROP FOREIGN KEY patient_exported_medical_record_ibfk_1;
ALTER TABLE patient_exported_medical_record CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_feedback DROP FOREIGN KEY patient_feedback_patient;
ALTER TABLE patient_feedback CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_location DROP FOREIGN KEY patient_location_ibfk_1;
ALTER TABLE patient_location CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_parent DROP FOREIGN KEY patient_parent_parent;
ALTER TABLE patient_parent DROP FOREIGN KEY patient_parent_patient;
ALTER TABLE patient_parent CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_parent CHANGE parent_patient_id parent_patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_pcp DROP FOREIGN KEY patient_pcp_ibfk_1;
ALTER TABLE patient_pcp CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_pharmacy_selection DROP FOREIGN KEY patient_pharmacy_selection_ibfk_1;
ALTER TABLE patient_pharmacy_selection CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_receipt DROP FOREIGN KEY patient_receipt_ibfk_1;
ALTER TABLE patient_receipt CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE patient_visit DROP FOREIGN KEY patient_visit_ibfk_1;
ALTER TABLE patient_visit CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE photo_intake_section DROP FOREIGN KEY photo_intake_section_ibfk_2;
ALTER TABLE photo_intake_section CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE rx_refill_request DROP FOREIGN KEY rx_refill_request_ibfk_5;
ALTER TABLE rx_refill_request CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE scheduled_message DROP FOREIGN KEY scheduled_message_ibfk_1;
ALTER TABLE scheduled_message CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE treatment_plan DROP FOREIGN KEY treatment_plan_ibfk_3;
ALTER TABLE treatment_plan CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
-- unclaimed_case_queue doesn't seem to have a foreign key constraint
ALTER TABLE unclaimed_case_queue CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE unlinked_dntf_treatment DROP FOREIGN KEY unlinked_dntf_treatment_ibfk_6;
ALTER TABLE unlinked_dntf_treatment CHANGE patient_id patient_id BIGINT UNSIGNED NOT NULL;

ALTER TABLE patient CHANGE id id BIGINT UNSIGNED NOT NULL;

ALTER TABLE credit_card ADD CONSTRAINT credit_card_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE doctor_queue ADD CONSTRAINT doctor_queue_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE doctor_transaction ADD CONSTRAINT doctor_transaction_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE health_log ADD CONSTRAINT health_log_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE info_intake ADD CONSTRAINT info_intake_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE parent_consent_proof ADD CONSTRAINT parent_consent_proof_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_address_selection ADD CONSTRAINT patient_address_selection_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_agreement ADD CONSTRAINT patient_agreement_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_care_provider_assignment ADD CONSTRAINT patient_care_provider_assignment_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_case ADD CONSTRAINT patient_case_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_emergency_contact ADD CONSTRAINT patient_emergency_contact_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_exported_medical_record ADD CONSTRAINT patient_exported_medical_record_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_feedback ADD CONSTRAINT patient_feedback_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_location ADD CONSTRAINT patient_location_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_parent ADD CONSTRAINT patient_parent_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_parent ADD CONSTRAINT patient_parent_parent_patient FOREIGN KEY (parent_patient_id) REFERENCES patient (id);
ALTER TABLE patient_pcp ADD CONSTRAINT patient_pcp_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_pharmacy_selection ADD CONSTRAINT patient_pharmacy_selection_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_receipt ADD CONSTRAINT patient_receipt_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE patient_visit ADD CONSTRAINT patient_visit_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE photo_intake_section ADD CONSTRAINT photo_intake_section_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE rx_refill_request ADD CONSTRAINT rx_refill_request_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE scheduled_message ADD CONSTRAINT scheduled_message_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE treatment_plan ADD CONSTRAINT treatment_plan_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE unclaimed_case_queue ADD CONSTRAINT unclaimed_case_queue_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
ALTER TABLE unlinked_dntf_treatment ADD CONSTRAINT unlinked_dntf_treatment_patient FOREIGN KEY (patient_id) REFERENCES patient (id);
