ALTER TABLE server_event
	ALTER COLUMN patient_id TYPE BIGINT,
	ALTER COLUMN account_id TYPE BIGINT,
	ALTER COLUMN doctor_id TYPE BIGINT,
	ALTER COLUMN visit_id TYPE BIGINT,
	ALTER COLUMN case_id TYPE BIGINT,
	ALTER COLUMN treatment_plan_id TYPE BIGINT;

ALTER TABLE client_event
	ALTER COLUMN patient_id TYPE BIGINT,
	ALTER COLUMN account_id TYPE BIGINT,
	ALTER COLUMN doctor_id TYPE BIGINT,
	ALTER COLUMN visit_id TYPE BIGINT,
	ALTER COLUMN case_id TYPE BIGINT;
